version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies - angularCli
          command: npm install @angular/cli
      - run:
          name: BUILD
          command: npm run build
      - run: ls -lh
      - persist_to_workspace:
          root: /home/circleci/project/dist/
          paths:
            - angular-app/dist       
orbs:
  cypress: cypress-io/cypress@1.29.0 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - cypress/install:
           build: "npm run build"
      - cypress/run:
           record: true
           parallel: true
           parallelism: 10

      
   
