version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12-browsers
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies - angularCli
          command: npm install @angular/cli
      - run:
          name: Testing Jest
          command: npm run test
      - run:
          name: BUILD
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop

      
   
