version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: npm -v
      - run: echo $PWD
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies - angularCli
          command: npm install @angular/cli