version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies - angularCli
          command: npm install @angular/cli
      - run:
          name: Testing Jest
          command: npm run test
      - run:
          name: BUILD
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/project
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: aws s3 sync dist/unicomerFront/ s3://unicomer-front-dev/ --delete --exact-timestamps;
  
  deploy-gcp:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk
        environment:
          STORAGE_BUCKET: angular-frontend-app
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Initialize gcloud
          command: /tmp/workspace/build/authgcloud.sh
      - run:
          name: list files
          command: ls /tmp/workspace/dist
      - run:
          name: deploy
          command: /tmp/workspace/build/deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - gcp
      # - deploy:
      #     requires:
      #       - build
      - deploy-gcp:
          requires:
            - build
