version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: 
          name: Install dependencies - angularCli
          command: npm install @angular/cli
      - run:
          name: Testing Jest
          command: npm run test
      - run:
          name: BUILD
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/project
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: aws s3 sync dist/unicomerFront/ s3://unicomer-front-dev/ --delete --exact-timestamps;
  run_cypress_tests:
    working_directory: ~/project/unicomerfrontdev
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: npm ci
      - run:
          name: Start Project
          command: npm run start
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running cypress tests
          command: npm run cypress:run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  deploy-gcp:
    working_directory: ~/project
    docker:
      - image: google/cloud-sdk
        environment:
          STORAGE_BUCKET: angular-frontend-app
    steps:
      - attach_workspace:
          at: .
      - run: chmod +x authgcloud.sh
      - run: chmod +x deploy.sh
      - run:
          name: Initialize gcloud
          command: ./authgcloud.sh
      - run:
          name: gcloud config show
          command:  gcloud config list         
      - run:
          name: list files
          command: ls dist/
      - run:
          name: deploy
          command: ./deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - run_cypress_tests:
          requires:
            - build
      - deploy:
          requires:
            - run_cypress_tests
            - gcp
      # - deploy:
      #     requires:
      #       - build
      - deploy-gcp:
          requires:
            - build
