version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies - angularCli
          command: npm install @angular/cli
      - run:
          name: Testing Jest
          command: npm run test
      - run:
          name: BUILD
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop

      
   
